server:
  host: "0.0.0.0"
  port: 8003
  mode: debug

service:
  name: community-service

mysql:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  user: ash
  password: ash_dev_password
  database: ash_dev
  charset: utf8mb4
  max_idle_conns: 5
  max_open_conns: 20

log:
  level: debug
  format: console
